services:
  api:
    ports:
      - "8050:8050"
    volumes:
      - /mnt/nextcloud-instant-uploads/tradutor/data:/data
  worker:
    volumes:
      - /mnt/nextcloud-instant-uploads/tradutor/data:/data
  watcher:
    volumes:
      - /mnt/nextcloud-instant-uploads/tradutor/data:/data
